name: storybook_ds
description: Storybook Uma forma de apresentar os componentes de qualquer Design System
homepage: https://github.com/jheimes-silveira/storybook_ds
version: 1.2.3+22

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  device_frame: ^1.2.0
  shared_preferences: ^2.5.0
  reflectable: ^4.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
